[build]
  command = "rm -rf node_modules && npm cache clean --force && npm install && npm run build"
  publish = "build"
  functions = "build/functions/"

[dev]
 command = "svelte-kit dev"
 
[functions]
  directory = "netlify/functions"
  node_bundler = "esbuild"